spring:
    datasource:
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
        driver-class-name: com.mysql.jdbc.Driver
        exceptionSorter: true
        filters: stat,wall,log4j
        initialSize: 5
        maxActive: 20
        maxPoolPreparedStatementPerConnectionSize: 20
        maxWait: 60000
        minEvictableIdleTimeMillis: 300000
        minIdle: 5
        password: conquer@2018.cn
        poolPreparedStatements: true
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8
        useGlobalDataSourceStat: true
        username: root
        validationQuery: SELECT 1 FROM t_user
    jpa:
        database: mysql
        hibernate:
            naming:
                strategy: org.hibernate.cfg.ImprovedNamingStrategy
        show-sql: true
    redis:
        database: 0
        host: 127.0.0.1
        password: ''
        pool:
            max-active: 10
            max-idle: 8
            max-wait: -1
            min-idle: 0
        port: 6379
        timeout: 0
